apiVersion: v1
kind: Service
metadata:
  name: application-server-project
  labels:
    app: application-server-project
spec:
  type: NodePort
  ports:
    - port: 8080
  selector:
    app: application-server-project
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: application-server-project
  labels:
    app: application-server-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: application-server-project
  template:
    metadata:
      labels:
        app: application-server-project
    spec:
      containers:
        - name: application-server-project
          image: application-server-project:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
