version: '3'

services:
  mysql:
    image: ivonet/mysql-quote-db:${VERSION:-1.0}
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    ports:
      - "8888:80"
    links:
      - mysql
    environment:
      - MYSQL_USERNAME=root
      - MYSQL_ROOT_PASSWORD=secret
      - PMA_HOST=mysql
    depends_on:
      - mysql
    networks:
      - backend

  application-server-project:
    image: ivonet/application-server-project
    build:
      context: ./application-server-project
    ports:
      - "8080:8080"
#      - "4848:4848"
    links:
      - mysql
    depends_on:
      - mysql
    networks:
      - frontend
      - backend

# TODO: add front-end

#  web:
#    build:
#      context: ./web
#      dockerfile: Dockerfile
#    image: web
#    ports:
#      - "3000:3000"
#    links:
#      - quote-service
#    depends_on:
#      - quote-service
#    networks:
#      - frontend

networks:
  frontend:
  backend:

volumes:
  mysql-data:
    driver: local
