FROM ivonet/payara-full-jndi-quote:1.0

#COPY ./artifact/application-server-project.war ${DEPLOY_DIR}
COPY ./artifact/application-server-project.war /opt/payara/payara5/glassfish/domains/domain1/autodeploy
