version: '3'

services:
  mysql:
    image: ivonet/mysql-quote-db:${VERSION:-1.0}
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    ports:
      - "8888:80"
    links:
      - mysql
    environment:
      - MYSQL_USERNAME=root
      - MYSQL_ROOT_PASSWORD=secret
      - PMA_HOST=mysql
    depends_on:
      - mysql
    networks:
      - backend

  quote-service:
    image: ivonet/payara-full-jndi-quote:${VERSION:-1.0}
    ports:
      - "8080:8080"
#      - "4848:4848"
    links:
      - mysql
    depends_on:
      - mysql
    networks:
      - backend
    volumes:
      - ./artifact:/autodeploy

networks:
  backend:

volumes:
  mysql-data:
    driver: local
