apiVersion: v1
kind: Service
metadata:
  name: uber-jar-project
  labels:
    app: uber-jar-project
spec:
  type: NodePort
  ports:
    - port: 8080
  selector:
    app: uber-jar-project
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: uber-jar-project
  labels:
    app: uber-jar-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uber-jar-project
  template:
    metadata:
      labels:
        app: uber-jar-project
    spec:
      containers:
        - name: uber-jar-project
          image: uber-jar-project:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
